//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовой_проект_РЕКЛАМА
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisements
    {
        public string ad_name { get; set; }
        public string broadcast { get; set; }
        public Nullable<byte> cl_id { get; set; }
        public Nullable<byte> emp_id { get; set; }
        public Nullable<int> interval { get; set; }
        public Nullable<System.TimeSpan> ad_time { get; set; }
        public string FIO_Passport { get; set; }
        public byte ad_id { get; set; }
    
        public virtual Air Air { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
