//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовой_проект_РЕКЛАМА
{
    using System;
    using System.Collections.Generic;
    
    public partial class Air
    {
        public Air()
        {
            this.Advertisements = new HashSet<Advertisements>();
        }
    
        public string broadcast { get; set; }
        public System.TimeSpan start_time { get; set; }
        public System.TimeSpan end_time { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual ICollection<Advertisements> Advertisements { get; set; }
    }
}
