//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовой_проект_РЕКЛАМА
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public Employees()
        {
            this.Advertisements = new HashSet<Advertisements>();
        }
    
        public byte emp_id { get; set; }
        public Nullable<byte> post_id { get; set; }
        public string emp_surname { get; set; }
        public string emp_name { get; set; }
        public string emp_lastname { get; set; }
        public Nullable<byte> emp_percent { get; set; }
        public System.DateTime date_hire { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string image_trip { get; set; }
    
        public virtual ICollection<Advertisements> Advertisements { get; set; }
        public virtual Posts Posts { get; set; }
    }
}
