//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовой_проект_РЕКЛАМА
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_StatisticsFIO
    {
        public string FIO_Login { get; set; }
        public string cl_surname { get; set; }
        public string cl_name { get; set; }
        public string cl_passport { get; set; }
        public string ad_name { get; set; }
        public Nullable<decimal> Income { get; set; }
        public byte ad_id { get; set; }
        public Nullable<System.TimeSpan> ad_time { get; set; }
    }
}
